export const enum EmployeeHolidayType {
  ANNUAL_HOLIDAY = 'ANNUAL_HOLIDAY',

  PUBLIC_HOLIDAY = 'PUBLIC_HOLIDAY',

  PARENTAL_LEAVE = 'PARENTAL_LEAVE',

  SICKNESS_ABSENCE = 'SICKNESS_ABSENCE',

  UNPAID_HOLIDAY = 'UNPAID_HOLIDAY',

  OTHER = 'OTHER',
}
