export const enum RelationType {
  CLIENT_UNFAVOURS_EMPLOYEE = 'CLIENT_UNFAVOURS_EMPLOYEE',

  EMPLOYEE_VISITED_CLIENT_BEFORE = 'EMPLOYEE_VISITED_CLIENT_BEFORE',

  CLIENT_PREFERRED_EMPLOYEE = 'CLIENT_PREFERRED_EMPLOYEE',
}
