export const enum ServiceUserEventType {
  ACCIDENT = 'ACCIDENT',

  INCIDENT = 'INCIDENT',

  SAFEGUARDING = 'SAFEGUARDING',

  MEDICAL_ERROR = 'MEDICAL_ERROR',

  COMPLIMENT = 'COMPLIMENT',

  COMPLAINCE = 'COMPLAINCE',

  COMMENT = 'COMMENT',

  MISSED_VISIT = 'MISSED_VISIT',
}
