export const enum Shift {
  MORNING_SHIFT = 'MORNING_SHIFT',

  AFTERNOON_SHIFT = 'AFTERNOON_SHIFT',

  EVENING_SHIFT = 'EVENING_SHIFT',

  NIGHTS_SHIFT = 'NIGHTS_SHIFT',

  AVAILABLE_ANY_SHIFT = 'AVAILABLE_ANY_SHIFT',
}
